spellchecker: aspell
matrix:
- name: markdown
  aspell:
    lang: en
  sources:
  - '*.md'
  - 'src/**/*.md'
  - 'scripts/**/*.md'
  pipeline:
  - pyspelling.filters.markdown
  dictionary:
    wordlists:
    - .wordlist.txt
    output: wordlist.dic
    encoding: utf-8
  default_encoding: utf-8
  expect_match: true
- name: restructuredtext
  aspell:
    lang: en
  sources:
  - 'docs/**/*.rst'
  pipeline:
  - pyspelling.filters.text
  dictionary:
    wordlists:
    - .wordlist.txt
    output: wordlist.dic
    encoding: utf-8
  default_encoding: utf-8
  expect_match: true
