# DKMS configuration for rocm_ernic eth+RDMA (rocm-xio)
#
# Two modules:
#   rocm_ernic_eth.ko  - ethernet driver
#   rocm_ernic_rdma.ko - RDMA driver
#
# SPDX-License-Identifier: GPL-2.0

PACKAGE_NAME="rocm-xio-ernic-eth-rdma"
PACKAGE_VERSION="0.1.0"

BUILT_MODULE_NAME[0]="rocm_ernic_eth"
DEST_MODULE_LOCATION[0]="/updates/dkms"

BUILT_MODULE_NAME[1]="rocm_ernic_rdma"
DEST_MODULE_LOCATION[1]="/updates/dkms"

AUTOINSTALL="yes"

MAKE="make -C ${kernel_source_dir} \
  M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build \
  modules"

CLEAN="make -C ${kernel_source_dir} \
  M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build \
  clean"
