/* Copyright (c) Advanced Micro Devices, Inc. All rights reserved.
 *
 * SPDX-License-Identifier: MIT
 *
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-rdma-vendor-headers.sh
 * Source: AMD Emulated RDMA NIC (rocm-ernic)
 */

#ifndef ROCM_ERNIC_RDMA_H
#define ROCM_ERNIC_RDMA_H

#include "../rdma-ep.h"

/*
 * ROCM-ERNIC (AMD Emulated RDMA NIC) Provider
 *
 * This is an emulated RDMA provider for testing and development
 */

// ROCM-ERNIC-specific constants
#define ROCM_ERNIC_MAX_SEND_WR 4096
#define ROCM_ERNIC_MAX_RECV_WR 4096
#define ROCM_ERNIC_MAX_SEND_SGE 16
#define ROCM_ERNIC_MAX_RECV_SGE 16

// ROCM-ERNIC-specific WQE opcodes
#define ROCM_ERNIC_WR_SEND 0x00
#define ROCM_ERNIC_WR_SEND_WITH_IMM 0x01
#define ROCM_ERNIC_WR_RDMA_WRITE 0x02
#define ROCM_ERNIC_WR_RDMA_WRITE_WITH_IMM 0x03
#define ROCM_ERNIC_WR_RDMA_READ 0x04

// ROCM-ERNIC-specific completion status
#define ROCM_ERNIC_WC_SUCCESS 0x00
#define ROCM_ERNIC_WC_LOC_LEN_ERR 0x01
#define ROCM_ERNIC_WC_LOC_QP_OP_ERR 0x02
#define ROCM_ERNIC_WC_LOC_PROT_ERR 0x03
#define ROCM_ERNIC_WC_REM_ACCESS_ERR 0x10

// ROCM-ERNIC WQE flags
#define ROCM_ERNIC_SEND_SIGNALED (1 << 0)
#define ROCM_ERNIC_SEND_SOLICITED (1 << 1)
#define ROCM_ERNIC_SEND_INLINE (1 << 2)
#define ROCM_ERNIC_SEND_FENCE (1 << 3)

// Helper function to set ROCM-ERNIC-specific WQE fields
__host__ __device__ static inline void
rocm_ernic_wqe_set_vendor_specific(struct rdma_wqe* wqe, uint32_t qp_num,
                                   bool signaled, bool fence) {
  uint64_t flags = 0;
  if (signaled)
    flags |= ROCM_ERNIC_SEND_SIGNALED;
  if (fence)
    flags |= ROCM_ERNIC_SEND_FENCE;
  wqe->vendor_specific = (static_cast<uint64_t>(qp_num) << 32) | flags;
}

// Helper function to extract ROCM-ERNIC-specific CQE fields
__host__ __device__ static inline uint32_t
rocm_ernic_cqe_get_qpn(const struct rdma_cqe* cqe) {
  return cqe->rocm_ernic.qpn;
}

#endif // ROCM_ERNIC_RDMA_H
