# DKMS configuration for bnxt_re with Direct Verbs support
#
# SPDX-License-Identifier: GPL-2.0

PACKAGE_NAME="bnxt-re-dv"
PACKAGE_VERSION="0.1"

BUILT_MODULE_NAME[0]="bnxt_re"
DEST_MODULE_LOCATION[0]="/updates/dkms"

AUTOINSTALL="yes"

MAKE="make -C ${kernel_source_dir} \
  M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build \
  modules"

CLEAN="make -C ${kernel_source_dir} \
  M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build \
  clean"
