/* Copyright (c) Advanced Micro Devices, Inc. All rights reserved.
 *
 * SPDX-License-Identifier: MIT
 *
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-rdma-vendor-headers.sh
 * Source: rdma-core repository providers/mlx5/
 */

#ifndef MLX5_RDMA_H
#define MLX5_RDMA_H

#include "../rdma-ep.h"

/*
 * MLX5 (Mellanox/NVIDIA ConnectX) RDMA Provider
 *
 * Reference: providers/mlx5/ from linux-rdma/rdma-core
 * Downloaded headers in include/external/rdma/mlx/ for reference
 */

// MLX5-specific WQE opcodes
#define MLX5_OPCODE_SEND 0x0A
#define MLX5_OPCODE_SEND_IMM 0x0B
#define MLX5_OPCODE_RDMA_WRITE 0x08
#define MLX5_OPCODE_RDMA_WRITE_IMM 0x09
#define MLX5_OPCODE_RDMA_READ 0x10

// MLX5-specific flags
#define MLX5_WQE_CTRL_SOLICITED (1 << 1)
#define MLX5_WQE_CTRL_FENCE (1 << 6)
#define MLX5_SEND_WQE_BB 64 // Basic block size

// MLX5-specific CQE fields
#define MLX5_CQE_SYNDROME_LOCAL_LENGTH_ERR 0x01
#define MLX5_CQE_SYNDROME_LOCAL_QP_OP_ERR 0x02
#define MLX5_CQE_SYNDROME_REMOTE_ACCESS_ERR 0x10

// Helper function to set MLX5-specific WQE fields
__host__ __device__ static inline void mlx5_wqe_set_vendor_specific(
  struct rdma_wqe* wqe, uint32_t qp_num, bool solicited, bool fence) {
  uint64_t flags = 0;
  if (solicited)
    flags |= MLX5_WQE_CTRL_SOLICITED;
  if (fence)
    flags |= MLX5_WQE_CTRL_FENCE;
  wqe->vendor_specific = (static_cast<uint64_t>(qp_num) << 32) | flags;
}

// Helper function to extract MLX5-specific CQE fields
__host__ __device__ static inline uint32_t mlx5_cqe_get_src_qp(
  const struct rdma_cqe* cqe) {
  return cqe->mlx5.src_qp;
}

__host__ __device__ static inline uint32_t mlx5_cqe_get_flags(
  const struct rdma_cqe* cqe) {
  return cqe->mlx5.flags;
}

//
// MLX5 Doorbell Ringing - Based on rocSHMEM GDA Pattern
//
// MLX5 uses BlueFlame (BF) registers for doorbell writes.
// Reference: rocSHMEM queue_pair_mlx5.cpp mlx5_ring_doorbell()
//
// Key insight: The doorbell pointer from mmap() can be used DIRECTLY
// from GPU kernels with __HIP_MEMORY_SCOPE_SYSTEM atomics!
//

/**
 * Ring MLX5 doorbell from GPU kernel
 *
 * @param doorbell_ptr Pointer to MLX5 BlueFlame register (from mmap)
 * @param db_val Doorbell value (typically WQE control segment)
 * @param sq_counter Send Queue counter/tail value
 *
 * Pattern from rocSHMEM GDA:
 * - Uses system-scope atomic store to traverse PCIe
 * - No HSA memory locking needed for NIC doorbells
 * - Unified virtual address space on AMD GPUs with Large BAR
 */
__device__ static inline void mlx5_ring_doorbell_gpu(
  volatile uint64_t* doorbell_ptr, uint64_t db_val, uint32_t sq_counter) {
  // Write to doorbell record (not directly visible, but semantically important)
  // In real MLX5, this would be: *dbrec = htobe32(sq_counter)

  // Ring the doorbell using system-scope atomic
  // This forces GPU to route write through PCIe to the NIC
  __hip_atomic_store(doorbell_ptr, db_val, __ATOMIC_SEQ_CST,
                     __HIP_MEMORY_SCOPE_SYSTEM);

  // Ensure all memory operations complete
  __threadfence_system();
}

/**
 * Ring MLX5 doorbell from CPU
 *
 * @param doorbell_ptr Pointer to MLX5 BlueFlame register
 * @param db_val Doorbell value
 * @param sq_counter Send Queue counter
 */
static inline void mlx5_ring_doorbell_cpu(volatile uint64_t* doorbell_ptr,
                                          uint64_t db_val,
                                          uint32_t sq_counter) {
  // CPU can write directly with memory fence
  __atomic_store_n(doorbell_ptr, db_val, __ATOMIC_SEQ_CST);
  __sync_synchronize();
}

#endif // MLX5_RDMA_H
