/* Copyright (c) Advanced Micro Devices, Inc. All rights reserved.
 *
 * SPDX-License-Identifier: MIT
 *
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-rdma-vendor-headers.sh
 * Source: rdma-core repository providers/vmw_pvrdma/
 */

#ifndef PVRDMA_RDMA_H
#define PVRDMA_RDMA_H

#include "../rdma-ep.h"

/*
 * PVRDMA (VMware Paravirtualized RDMA) Provider
 *
 * Reference: providers/vmw_pvrdma/ from linux-rdma/rdma-core
 * Downloaded headers in include/external/rdma/pvrdma/ for reference
 */

// PVRDMA-specific constants
#define PVRDMA_MAX_SEND_WR 4096
#define PVRDMA_MAX_RECV_WR 4096
#define PVRDMA_MAX_SEND_SGE 4
#define PVRDMA_MAX_RECV_SGE 4

// PVRDMA-specific WQE opcodes
#define PVRDMA_WR_SEND 0x00
#define PVRDMA_WR_SEND_WITH_IMM 0x01
#define PVRDMA_WR_RDMA_WRITE 0x02
#define PVRDMA_WR_RDMA_WRITE_WITH_IMM 0x03
#define PVRDMA_WR_RDMA_READ 0x04

// PVRDMA-specific completion status
#define PVRDMA_WC_SUCCESS 0x00
#define PVRDMA_WC_LOC_LEN_ERR 0x01
#define PVRDMA_WC_LOC_QP_OP_ERR 0x02
#define PVRDMA_WC_LOC_PROT_ERR 0x03
#define PVRDMA_WC_REM_ACCESS_ERR 0x10

// PVRDMA WQE flags
#define PVRDMA_SEND_SIGNALED (1 << 0)
#define PVRDMA_SEND_SOLICITED (1 << 1)
#define PVRDMA_SEND_INLINE (1 << 2)
#define PVRDMA_SEND_FENCE (1 << 3)

// Helper function to set PVRDMA-specific WQE fields
__host__ __device__ static inline void pvrdma_wqe_set_vendor_specific(
  struct rdma_wqe* wqe, uint32_t qp_num, bool signaled, bool fence) {
  uint64_t flags = 0;
  if (signaled)
    flags |= PVRDMA_SEND_SIGNALED;
  if (fence)
    flags |= PVRDMA_SEND_FENCE;
  wqe->vendor_specific = (static_cast<uint64_t>(qp_num) << 32) | flags;
}

// Helper function to extract PVRDMA-specific CQE fields
__host__ __device__ static inline uint32_t pvrdma_cqe_get_qpn(
  const struct rdma_cqe* cqe) {
  return cqe->pvrdma.qpn;
}

//
// PVRDMA (VMware Paravirtualized RDMA) Doorbell Ringing
//
// PVRDMA uses UAR (User Access Region) for doorbells.
// Reference: vmw_pvrdma-abi.h from rdma-core
//

// PVRDMA UAR doorbell offsets and bits (from vmw_pvrdma-abi.h)
#define PVRDMA_UAR_QP_OFFSET 0       // QP doorbell offset
#define PVRDMA_UAR_QP_SEND (1 << 30) // Send bit
#define PVRDMA_UAR_QP_RECV (1 << 31) // Recv bit
#define PVRDMA_UAR_CQ_OFFSET 4       // CQ doorbell offset

/**
 * Encode PVRDMA doorbell value
 *
 * @param qp_handle Queue Pair handle (24 bits)
 * @param is_send true for Send Queue, false for Receive Queue
 * @return Encoded 32-bit doorbell value
 */
__host__ __device__ static inline uint32_t pvrdma_encode_doorbell(
  uint32_t qp_handle, bool is_send) {
  uint32_t db_val = qp_handle & 0x00FFFFFF; // Bottom 24 bits
  if (is_send) {
    db_val |= PVRDMA_UAR_QP_SEND;
  } else {
    db_val |= PVRDMA_UAR_QP_RECV;
  }
  return db_val;
}

/**
 * Ring PVRDMA doorbell from GPU kernel
 *
 * @param uar_base Pointer to UAR base address (from mmap)
 * @param qp_handle Queue Pair handle
 * @param is_send true for Send Queue, false for Receive Queue
 */
__device__ static inline void pvrdma_ring_doorbell_gpu(
  volatile uint32_t* uar_base, uint32_t qp_handle, bool is_send) {
  // Doorbell is at offset 0 within UAR
  volatile uint32_t* doorbell_ptr = uar_base +
                                    (PVRDMA_UAR_QP_OFFSET / sizeof(uint32_t));
  uint32_t db_val = pvrdma_encode_doorbell(qp_handle, is_send);

  // Ring doorbell using system-scope atomic (rocSHMEM pattern)
  __hip_atomic_store(doorbell_ptr, db_val, __ATOMIC_SEQ_CST,
                     __HIP_MEMORY_SCOPE_SYSTEM);

  __threadfence_system();
}

/**
 * Ring PVRDMA doorbell from CPU
 */
static inline void pvrdma_ring_doorbell_cpu(volatile uint32_t* uar_base,
                                            uint32_t qp_handle, bool is_send) {
  volatile uint32_t* doorbell_ptr = uar_base +
                                    (PVRDMA_UAR_QP_OFFSET / sizeof(uint32_t));
  uint32_t db_val = pvrdma_encode_doorbell(qp_handle, is_send);
  __atomic_store_n(doorbell_ptr, db_val, __ATOMIC_SEQ_CST);
  __sync_synchronize();
}

#endif // PVRDMA_RDMA_H
