/* Copyright (c) Advanced Micro Devices, Inc. All rights reserved.
 *
 * SPDX-License-Identifier: MIT
 *
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-rdma-vendor-headers.sh
 * Source: rdma-core repository providers/bnxt_re/
 */

#ifndef BNXT_RDMA_H
#define BNXT_RDMA_H

#include "../rdma-ep.h"

/*
 * BNXT_RE (Broadcom NetXtreme RDMA) Provider
 *
 * Reference: providers/bnxt_re/ from linux-rdma/rdma-core
 * Downloaded headers in include/external/rdma/bnxt/ for reference
 */

// BNXT-specific WQE sizes and limits
#define BNXT_RE_MAX_WQE_SIZE 128
#define BNXT_RE_MAX_INLINE_DATA 96
#define BNXT_RE_WQE_SIZE 64

// BNXT-specific operation types
#define BNXT_RE_WR_OPCD_SEND 0x00
#define BNXT_RE_WR_OPCD_SEND_WITH_IMM 0x01
#define BNXT_RE_WR_OPCD_RDMA_WRITE 0x04
#define BNXT_RE_WR_OPCD_RDMA_WRITE_WITH_IMM 0x05
#define BNXT_RE_WR_OPCD_RDMA_READ 0x06

// BNXT-specific CQE status codes
#define BNXT_RE_RSP_ST_OK 0x00
#define BNXT_RE_RSP_ST_LOCAL_LENGTH_ERR 0x01
#define BNXT_RE_RSP_ST_LOCAL_PROTECTION_ERR 0x04
#define BNXT_RE_RSP_ST_REMOTE_ACCESS_ERR 0x10

// Helper function to set BNXT-specific WQE fields
__host__ __device__ static inline void bnxt_wqe_set_vendor_specific(
  struct rdma_wqe* wqe, uint32_t sq_prod_idx, uint32_t inline_len) {
  wqe->vendor_specific = (static_cast<uint64_t>(sq_prod_idx) << 32) |
                         inline_len;
}

// Helper function to extract BNXT-specific CQE fields
__host__ __device__ static inline uint32_t bnxt_cqe_get_sq_cons_idx(
  const struct rdma_cqe* cqe) {
  return cqe->bnxt.sq_cons_idx;
}

__host__ __device__ static inline uint32_t bnxt_cqe_get_cq_cons_idx(
  const struct rdma_cqe* cqe) {
  return cqe->bnxt.cq_cons_idx;
}

//
// BNXT_RE Doorbell Ringing - Based on Broadcom NetXtreme Specification
//
// BNXT uses a structured doorbell format with queue type and index.
// Reference: bnxt_re-abi.h from rdma-core
//

// BNXT doorbell queue types (from bnxt_re-abi.h)
#define BNXT_RE_QUE_TYPE_SQ 0x00
#define BNXT_RE_QUE_TYPE_RQ 0x01
#define BNXT_RE_QUE_TYPE_CQ 0x04

// BNXT doorbell field masks and shifts
#define BNXT_RE_DB_INDX_MASK 0xFFFFFFUL
#define BNXT_RE_DB_QID_MASK 0xFFFFFUL
#define BNXT_RE_DB_TYP_MASK 0x0FUL
#define BNXT_RE_DB_TYP_SHIFT 0x1C

/**
 * Encode BNXT doorbell value
 *
 * @param queue_id Queue identifier (20 bits)
 * @param queue_type Queue type (SQ/RQ/CQ)
 * @param index Queue index/tail (24 bits)
 * @return Encoded 64-bit doorbell value
 */
__host__ __device__ static inline uint64_t bnxt_encode_doorbell(
  uint32_t queue_id, uint32_t queue_type, uint32_t index) {
  uint64_t db_val = 0;
  // Lower 32 bits: index
  db_val |= (index & BNXT_RE_DB_INDX_MASK);
  // Upper 32 bits: queue type and queue ID
  db_val |= ((uint64_t)(queue_type & BNXT_RE_DB_TYP_MASK)
             << (32 + BNXT_RE_DB_TYP_SHIFT));
  db_val |= ((uint64_t)(queue_id & BNXT_RE_DB_QID_MASK) << 32);
  return db_val;
}

/**
 * Ring BNXT doorbell from GPU kernel
 *
 * @param doorbell_ptr Pointer to BNXT doorbell register (from mmap)
 * @param queue_id Queue identifier
 * @param queue_type Queue type (SQ/RQ/CQ)
 * @param index Queue tail index
 */
__device__ static inline void bnxt_ring_doorbell_gpu(
  volatile uint64_t* doorbell_ptr, uint32_t queue_id, uint32_t queue_type,
  uint32_t index) {
  uint64_t db_val = bnxt_encode_doorbell(queue_id, queue_type, index);

  // Ring doorbell using system-scope atomic (rocSHMEM pattern)
  __hip_atomic_store(doorbell_ptr, db_val, __ATOMIC_SEQ_CST,
                     __HIP_MEMORY_SCOPE_SYSTEM);

  __threadfence_system();
}

/**
 * Ring BNXT doorbell from CPU
 */
static inline void bnxt_ring_doorbell_cpu(volatile uint64_t* doorbell_ptr,
                                          uint32_t queue_id,
                                          uint32_t queue_type, uint32_t index) {
  uint64_t db_val = bnxt_encode_doorbell(queue_id, queue_type, index);
  __atomic_store_n(doorbell_ptr, db_val, __ATOMIC_SEQ_CST);
  __sync_synchronize();
}

#endif // BNXT_RDMA_H
