#!/bin/bash
# Generate endpoint dispatch implementation file

ENDPOINTS_DIR="$1"
OUTPUT_FILE="$2"

if [ -z "$ENDPOINTS_DIR" ] || [ -z "$OUTPUT_FILE" ]; then
  echo "Usage: $0 <endpoints_dir> <output_file>"
  exit 1
fi

# Find all endpoint directories
ENDPOINTS=$(find "$ENDPOINTS_DIR" -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | sort)

# Start generating the file
cat > "$OUTPUT_FILE" << 'EOF'
/* Copyright (c) Advanced Micro Devices, Inc. All rights reserved.
 *
 * SPDX-License-Identifier: MIT
 *
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-endpoint-dispatch.sh
 */

#include "axiio-endpoints.h"
EOF

# Generate includes for all endpoints
echo "" >> "$OUTPUT_FILE"
echo "// Auto-generated endpoint includes" >> "$OUTPUT_FILE"
for ep in $ENDPOINTS; do
  echo "#include \"${ep}.h\"" >> "$OUTPUT_FILE"
done

echo "" >> "$OUTPUT_FILE"

# Generate forward declarations
for ep in $ENDPOINTS; do
  EP_UNDERSCORE=$(echo "$ep" | tr '-' '_')
  
  cat >> "$OUTPUT_FILE" << FORWARD_EOF

// Forward declarations for ${ep} functions
extern "C" {
__host__ __device__ void ${EP_UNDERSCORE}_emulateEndpoint(unsigned, sqeType_s*,
                                                 cqeType_s*);
__device__ void ${EP_UNDERSCORE}_driveEndpoint(unsigned, sqeType_s*, cqeType_s*,
                                      unsigned long long int*,
                                      unsigned long long int*);
}
FORWARD_EOF
done

# Generate emulateEndpointDispatch function
cat >> "$OUTPUT_FILE" << 'EMULATE_START'

// Static dispatch implementations that don't require object dereferencing
__host__ __device__ void axiioEndPoint::emulateEndpointDispatch(
  EndpointType type, unsigned sqeIterations, sqeType* sqeAddr,
  cqeType* cqeAddr) {
  switch (type) {
EMULATE_START

# Generate switch cases for emulate
FIRST_EP=""
for ep in $ENDPOINTS; do
  EP_UPPER=$(echo "$ep" | tr '[:lower:]-' '[:upper:]_')
  EP_UNDERSCORE=$(echo "$ep" | tr '-' '_')
  
  if [ -z "$FIRST_EP" ]; then
    FIRST_EP="$EP_UNDERSCORE"
  fi
  
  cat >> "$OUTPUT_FILE" << CASE_EOF
    case EndpointType::${EP_UPPER}:
      ${EP_UNDERSCORE}_emulateEndpoint(sqeIterations, sqeAddr, cqeAddr);
      break;
CASE_EOF
done

# Add default case
cat >> "$OUTPUT_FILE" << 'EMULATE_END'
    default:
      // Default to first discovered endpoint
EMULATE_END

echo "      ${FIRST_EP}_emulateEndpoint(sqeIterations, sqeAddr, cqeAddr);" >> "$OUTPUT_FILE"

cat >> "$OUTPUT_FILE" << 'EMULATE_CLOSE'
      break;
  }
}
EMULATE_CLOSE

# Generate driveEndpointDispatch function
cat >> "$OUTPUT_FILE" << 'DRIVE_START'

__device__ void axiioEndPoint::driveEndpointDispatch(
  EndpointType type, unsigned sqeIterations, sqeType* sqeAddr, cqeType* cqeAddr,
  unsigned long long int* startTime, unsigned long long int* endTime) {
  switch (type) {
DRIVE_START

# Generate switch cases for drive
for ep in $ENDPOINTS; do
  EP_UPPER=$(echo "$ep" | tr '[:lower:]-' '[:upper:]_')
  EP_UNDERSCORE=$(echo "$ep" | tr '-' '_')
  
  cat >> "$OUTPUT_FILE" << CASE_EOF
    case EndpointType::${EP_UPPER}:
      ${EP_UNDERSCORE}_driveEndpoint(sqeIterations, sqeAddr, cqeAddr, startTime,
                            endTime);
      break;
CASE_EOF
done

# Add default case
cat >> "$OUTPUT_FILE" << 'DRIVE_END'
    default:
      // Default to first discovered endpoint
DRIVE_END

echo "      ${FIRST_EP}_driveEndpoint(sqeIterations, sqeAddr, cqeAddr, startTime," >> "$OUTPUT_FILE"
echo "                            endTime);" >> "$OUTPUT_FILE"

cat >> "$OUTPUT_FILE" << 'DRIVE_CLOSE'
      break;
  }
}
DRIVE_CLOSE

# Generate member function wrappers
cat >> "$OUTPUT_FILE" << 'WRAPPERS_EOF'

// Member function wrappers (require object in GPU-accessible memory)
__host__ __device__ void axiioEndPoint::emulateEndpoint(unsigned sqeIterations,
                                                        sqeType* sqeAddr,
                                                        cqeType* cqeAddr) {
  emulateEndpointDispatch(endpointType, sqeIterations, sqeAddr, cqeAddr);
}

__device__ void axiioEndPoint::driveEndpoint(unsigned sqeIterations,
                                             sqeType* sqeAddr, cqeType* cqeAddr,
                                             unsigned long long int* startTime,
                                             unsigned long long int* endTime) {
  driveEndpointDispatch(endpointType, sqeIterations, sqeAddr, cqeAddr,
                        startTime, endTime);
}
WRAPPERS_EOF

echo "Generated endpoint dispatch: $OUTPUT_FILE"

