#!/bin/bash
# Generate all endpoint-related files (registry, dispatch, includes)
# This script consolidates the functionality of:
#   - generate-endpoint-registry.sh
#   - generate-endpoint-dispatch.sh
#   - generate-endpoint-includes.sh

ENDPOINTS_DIR="$1"
REGISTRY_OUTPUT="$2"
DISPATCH_OUTPUT="$3"
INCLUDES_OUTPUT="$4"

if [ -z "$ENDPOINTS_DIR" ] || [ -z "$REGISTRY_OUTPUT" ] || \
   [ -z "$DISPATCH_OUTPUT" ] || [ -z "$INCLUDES_OUTPUT" ]; then
  echo "Usage: $0 <endpoints_dir> <registry_output> <dispatch_output> <includes_output>"
  exit 1
fi

# Find all endpoint directories
ENDPOINTS=$(find "$ENDPOINTS_DIR" -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | sort)

# Helper function to convert endpoint name to define name
get_endpoint_define() {
  local ep="$1"
  case "$ep" in
    test-ep)
      echo "TEST"
      ;;
    nvme-ep)
      echo "NVME"
      ;;
    nvme-simple-ep)
      echo "NVME_SIMPLE"
      ;;
    sdma-ep)
      echo "SDMA"
      ;;
    rdma-ep)
      echo "RDMA"
      ;;
    *)
      # Default: convert nvme-simple-ep -> NVME_SIMPLE_EP, then remove _EP
      echo "$ep" | sed 's/-ep$//' | sed 's/-/_/g' | tr '[:lower:]' '[:upper:]'
      ;;
  esac
}

# ============================================================================
# Generate endpoint registry (with enum)
# ============================================================================
cat > "$REGISTRY_OUTPUT" << 'REGISTRY_EOF'
/* Copyright (c) Advanced Micro Devices, Inc. All rights reserved.
 *
 * SPDX-License-Identifier: MIT
 *
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-endpoint-files.sh
 */

#ifndef AXIIO_ENDPOINT_REGISTRY_GEN_H
#define AXIIO_ENDPOINT_REGISTRY_GEN_H

// Endpoint definitions

// Auto-generated EndpointType enum
enum class EndpointType {
REGISTRY_EOF

FIRST_ENUM=1
for ep in $ENDPOINTS; do
  EP_UPPER=$(echo "$ep" | tr '[:lower:]-' '[:upper:]_')
  if [ $FIRST_ENUM -eq 1 ]; then
    echo "  ${EP_UPPER}," >> "$REGISTRY_OUTPUT"
    FIRST_ENUM=0
  else
    echo "  ${EP_UPPER}," >> "$REGISTRY_OUTPUT"
  fi
done

cat >> "$REGISTRY_OUTPUT" << 'REGISTRY_EOF'
  UNKNOWN
};

// Auto-discovered endpoints (numeric defines)
REGISTRY_EOF

INDEX=0
for ep in $ENDPOINTS; do
  EP_UPPER=$(echo "$ep" | tr '[:lower:]-' '[:upper:]_')
  echo "#define ENDPOINT_${EP_UPPER} ${INDEX}" >> "$REGISTRY_OUTPUT"
  ((INDEX++))
done

echo "" >> "$REGISTRY_OUTPUT"
echo "// Endpoint metadata" >> "$REGISTRY_OUTPUT"
echo "#define ENDPOINT_REGISTRY_ENTRIES { \\" >> "$REGISTRY_OUTPUT"

FIRST=1
for ep in $ENDPOINTS; do
  DESC_FILE="$ENDPOINTS_DIR/$ep/DESCRIPTION"
  if [ -f "$DESC_FILE" ]; then
    DESC=$(cat "$DESC_FILE")
  else
    DESC=$(echo "$ep" | sed 's/-ep$/ endpoint/' | sed 's/-/ /g')
  fi
  
  if [ $FIRST -eq 0 ]; then
    echo ", \\" >> "$REGISTRY_OUTPUT"
  fi
  FIRST=0
  
  EP_UPPER=$(echo "$ep" | tr '[:lower:]-' '[:upper:]_')
  echo -n "  {\"$ep\", \"$DESC\", EndpointType::${EP_UPPER}}" >> "$REGISTRY_OUTPUT"
done

cat >> "$REGISTRY_OUTPUT" << 'REGISTRY_EOF'
 \
}

#endif // AXIIO_ENDPOINT_REGISTRY_GEN_H
REGISTRY_EOF

echo "Generated endpoint registry: $REGISTRY_OUTPUT"

# ============================================================================
# Generate endpoint dispatch
# ============================================================================
cat > "$DISPATCH_OUTPUT" << 'DISPATCH_EOF'
/* Copyright (c) Advanced Micro Devices, Inc. All rights reserved.
 *
 * SPDX-License-Identifier: MIT
 *
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-endpoint-files.sh
 */

#include "axiio-endpoints.h"
DISPATCH_EOF

echo "" >> "$DISPATCH_OUTPUT"
echo "// Auto-generated endpoint includes" >> "$DISPATCH_OUTPUT"
for ep in $ENDPOINTS; do
  echo "#include \"${ep}.h\"" >> "$DISPATCH_OUTPUT"
done

echo "" >> "$DISPATCH_OUTPUT"

for ep in $ENDPOINTS; do
  EP_UNDERSCORE=$(echo "$ep" | tr '-' '_')
  
  cat >> "$DISPATCH_OUTPUT" << FORWARD_EOF

// Forward declarations for ${ep} functions
extern "C" {
__host__ __device__ void ${EP_UNDERSCORE}_emulateEndpoint(unsigned, sqeType_s*,
                                                 cqeType_s*);
__device__ void ${EP_UNDERSCORE}_driveEndpoint(unsigned, sqeType_s*, cqeType_s*,
                                      unsigned long long int*,
                                      unsigned long long int*);
}
FORWARD_EOF
done

cat >> "$DISPATCH_OUTPUT" << 'DISPATCH_EMULATE_START'

// Static dispatch implementations that don't require object dereferencing
__host__ __device__ void axiioEndPoint::emulateEndpointDispatch(
  EndpointType type, unsigned sqeIterations, sqeType* sqeAddr,
  cqeType* cqeAddr) {
  switch (type) {
DISPATCH_EMULATE_START

FIRST_EP=""
for ep in $ENDPOINTS; do
  EP_UPPER=$(echo "$ep" | tr '[:lower:]-' '[:upper:]_')
  EP_UNDERSCORE=$(echo "$ep" | tr '-' '_')
  
  if [ -z "$FIRST_EP" ]; then
    FIRST_EP="$EP_UNDERSCORE"
  fi
  
  cat >> "$DISPATCH_OUTPUT" << CASE_EOF
    case EndpointType::${EP_UPPER}:
      ${EP_UNDERSCORE}_emulateEndpoint(sqeIterations, sqeAddr, cqeAddr);
      break;
CASE_EOF
done

cat >> "$DISPATCH_OUTPUT" << 'DISPATCH_EMULATE_END'
    default:
      // Default to first discovered endpoint
DISPATCH_EMULATE_END

echo "      ${FIRST_EP}_emulateEndpoint(sqeIterations, sqeAddr, cqeAddr);" >> "$DISPATCH_OUTPUT"

cat >> "$DISPATCH_OUTPUT" << 'DISPATCH_EMULATE_CLOSE'
      break;
  }
}

DISPATCH_EMULATE_CLOSE

cat >> "$DISPATCH_OUTPUT" << 'DISPATCH_DRIVE_START'

__device__ void axiioEndPoint::driveEndpointDispatch(
  EndpointType type, unsigned sqeIterations, sqeType* sqeAddr, cqeType* cqeAddr,
  unsigned long long int* startTime, unsigned long long int* endTime) {
  switch (type) {
DISPATCH_DRIVE_START

for ep in $ENDPOINTS; do
  EP_UPPER=$(echo "$ep" | tr '[:lower:]-' '[:upper:]_')
  EP_UNDERSCORE=$(echo "$ep" | tr '-' '_')
  
  cat >> "$DISPATCH_OUTPUT" << CASE_EOF
    case EndpointType::${EP_UPPER}:
      ${EP_UNDERSCORE}_driveEndpoint(sqeIterations, sqeAddr, cqeAddr, startTime,
                            endTime);
      break;
CASE_EOF
done

cat >> "$DISPATCH_OUTPUT" << 'DISPATCH_DRIVE_END'
    default:
      // Default to first discovered endpoint
DISPATCH_DRIVE_END

echo "      ${FIRST_EP}_driveEndpoint(sqeIterations, sqeAddr, cqeAddr, startTime," >> "$DISPATCH_OUTPUT"
echo "                            endTime);" >> "$DISPATCH_OUTPUT"

cat >> "$DISPATCH_OUTPUT" << 'DISPATCH_DRIVE_CLOSE'
      break;
  }
}

DISPATCH_DRIVE_CLOSE

cat >> "$DISPATCH_OUTPUT" << 'DISPATCH_WRAPPERS_EOF'

// Member function wrappers (require object in GPU-accessible memory)
__host__ __device__ void axiioEndPoint::emulateEndpoint(unsigned sqeIterations,
                                                        sqeType* sqeAddr,
                                                        cqeType* cqeAddr) {
  emulateEndpointDispatch(endpointType, sqeIterations, sqeAddr, cqeAddr);
}

__device__ void axiioEndPoint::driveEndpoint(unsigned sqeIterations,
                                             sqeType* sqeAddr, cqeType* cqeAddr,
                                             unsigned long long int* startTime,
                                             unsigned long long int* endTime) {
  driveEndpointDispatch(endpointType, sqeIterations, sqeAddr, cqeAddr,
                        startTime, endTime);
}
DISPATCH_WRAPPERS_EOF

echo "Generated endpoint dispatch: $DISPATCH_OUTPUT"

# ============================================================================
# Generate endpoint includes
# ============================================================================
cat > "$INCLUDES_OUTPUT" << 'INCLUDES_EOF'
/* Copyright (c) Advanced Micro Devices, Inc. All rights reserved.
 *
 * SPDX-License-Identifier: MIT
 *
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-endpoint-files.sh
 */

// Include endpoint-specific headers to get their size definitions
INCLUDES_EOF

FIRST=1
for ep in $ENDPOINTS; do
  EP_UPPER=$(echo "$ep" | tr '[:lower:]-' '[:upper:]_')
  EP_DEFINE=$(get_endpoint_define "$ep")
  EP_HEADER="${ep}.h"
  SQE_SIZE_DEFINE="${EP_UPPER}_SQE_SIZE"
  CQE_SIZE_DEFINE="${EP_UPPER}_CQE_SIZE"
  
  if [ $FIRST -eq 1 ]; then
    echo "#if defined(AXIIO_ENDPOINT_${EP_DEFINE})" >> "$INCLUDES_OUTPUT"
    FIRST=0
  else
    echo "#elif defined(AXIIO_ENDPOINT_${EP_DEFINE})" >> "$INCLUDES_OUTPUT"
  fi
  
  echo "#include \"${EP_HEADER}\"" >> "$INCLUDES_OUTPUT"
  echo "#define AXIIO_SQE_SIZE ${SQE_SIZE_DEFINE}" >> "$INCLUDES_OUTPUT"
  echo "#define AXIIO_CQE_SIZE ${CQE_SIZE_DEFINE}" >> "$INCLUDES_OUTPUT"
done

cat >> "$INCLUDES_OUTPUT" << 'INCLUDES_EOF'
#else
// Default sizes if no specific endpoint is defined
#define AXIIO_SQE_SIZE 64
#define AXIIO_CQE_SIZE 16
#endif
INCLUDES_EOF

echo "Generated endpoint includes: $INCLUDES_OUTPUT"

