#!/bin/bash
# Generate endpoint registry header file

ENDPOINTS_DIR="$1"
OUTPUT_FILE="$2"

if [ -z "$ENDPOINTS_DIR" ] || [ -z "$OUTPUT_FILE" ]; then
  echo "Usage: $0 <endpoints_dir> <output_file>"
  exit 1
fi

# Start generating the header
cat > "$OUTPUT_FILE" << 'EOF'
/* Copyright (c) Advanced Micro Devices, Inc. All rights reserved.
 *
 * SPDX-License-Identifier: MIT
 *
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-endpoint-registry.sh
 */

#ifndef AXIIO_ENDPOINT_REGISTRY_GEN_H
#define AXIIO_ENDPOINT_REGISTRY_GEN_H

// Endpoint definitions
EOF

# Find all endpoint directories and generate enum entries
ENDPOINTS=$(find "$ENDPOINTS_DIR" -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | sort)

# Generate enum
echo "" >> "$OUTPUT_FILE"
echo "// Auto-discovered endpoints" >> "$OUTPUT_FILE"

INDEX=0
for ep in $ENDPOINTS; do
  EP_UPPER=$(echo "$ep" | tr '[:lower:]-' '[:upper:]_')
  echo "#define ENDPOINT_${EP_UPPER} ${INDEX}" >> "$OUTPUT_FILE"
  ((INDEX++))
done

# Generate descriptions (try to read from endpoint metadata if available)
echo "" >> "$OUTPUT_FILE"
echo "// Endpoint metadata" >> "$OUTPUT_FILE"
echo "#define ENDPOINT_REGISTRY_ENTRIES { \\" >> "$OUTPUT_FILE"

FIRST=1
for ep in $ENDPOINTS; do
  # Try to read description from endpoint header or use default
  DESC_FILE="$ENDPOINTS_DIR/$ep/DESCRIPTION"
  if [ -f "$DESC_FILE" ]; then
    DESC=$(cat "$DESC_FILE")
  else
    # Generate a description based on endpoint name
    DESC=$(echo "$ep" | sed 's/-ep$/ endpoint/' | sed 's/-/ /g')
  fi
  
  if [ $FIRST -eq 0 ]; then
    echo ", \\" >> "$OUTPUT_FILE"
  fi
  FIRST=0
  
  EP_UPPER=$(echo "$ep" | tr '[:lower:]-' '[:upper:]_')
  echo -n "  {\"$ep\", \"$DESC\", EndpointType::${EP_UPPER}}" >> "$OUTPUT_FILE"
done

echo " \\" >> "$OUTPUT_FILE"
echo "}" >> "$OUTPUT_FILE"

# Close the header
cat >> "$OUTPUT_FILE" << 'EOF'

#endif // AXIIO_ENDPOINT_REGISTRY_GEN_H
EOF

echo "Generated endpoint registry: $OUTPUT_FILE"

