/* Copyright (c) Advanced Micro Devices, Inc. All rights reserved.
 *
 * SPDX-License-Identifier: MIT
 *
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-rdma-vendor-headers.sh
 * Source: rdma-core repository providers/ionic/
 */

#ifndef IONIC_RDMA_H
#define IONIC_RDMA_H

#include "../rdma-ep.h"

/*
 * IONIC (Pensando Ionic RDMA) Provider
 *
 * Reference: providers/ionic/ from linux-rdma/rdma-core
 * Downloaded headers in include/external/rdma/ionic/ for reference
 */

// Ionic-specific constants
#define IONIC_MAX_SEND_WR 16384
#define IONIC_MAX_RECV_WR 16384
#define IONIC_MAX_SEND_SGE 1
#define IONIC_MAX_RECV_SGE 1

// Ionic-specific WQE opcodes
#define IONIC_OP_SEND 0x00
#define IONIC_OP_SEND_WITH_IMM 0x01
#define IONIC_OP_WRITE 0x02
#define IONIC_OP_WRITE_WITH_IMM 0x03
#define IONIC_OP_READ 0x04

// Ionic-specific completion status
#define IONIC_WC_SUCCESS 0x00
#define IONIC_WC_GENERAL_ERR 0x01
#define IONIC_WC_LOCAL_LENGTH_ERR 0x02
#define IONIC_WC_LOCAL_PROT_ERR 0x03
#define IONIC_WC_REMOTE_ACCESS_ERR 0x04

// Ionic WQE header flags
#define IONIC_SEND_SIGNALED (1 << 0)
#define IONIC_SEND_SOLICITED (1 << 1)
#define IONIC_SEND_INLINE (1 << 2)
#define IONIC_SEND_FENCE (1 << 3)

// Helper function to set Ionic-specific WQE fields
__host__ __device__ static inline void ionic_wqe_set_vendor_specific(
  struct rdma_wqe* wqe, uint32_t qp_num, bool signaled, bool fence) {
  uint64_t flags = 0;
  if (signaled)
    flags |= IONIC_SEND_SIGNALED;
  if (fence)
    flags |= IONIC_SEND_FENCE;
  wqe->vendor_specific = (static_cast<uint64_t>(qp_num) << 32) | flags;
}

// Helper function to extract Ionic-specific CQE fields
__host__ __device__ static inline uint32_t ionic_cqe_get_qpn(
  const struct rdma_cqe* cqe) {
  return cqe->ionic.qpn;
}

//
// IONIC (Pensando) Doorbell Ringing
//
// Pensando IONIC uses a simpler doorbell format.
// Reference: ionic-abi.h from rdma-core
//

/**
 * Ring IONIC doorbell from GPU kernel
 *
 * @param doorbell_ptr Pointer to IONIC doorbell register (from mmap)
 * @param qp_id Queue Pair identifier
 * @param wqe_index Work Queue Entry index/tail
 */
__device__ static inline void ionic_ring_doorbell_gpu(
  volatile uint32_t* doorbell_ptr, uint32_t qp_id, uint32_t wqe_index) {
  // IONIC doorbell format (simplified):
  // Lower 16 bits: WQE index
  // Upper 16 bits: QP ID
  uint32_t db_val = ((qp_id & 0xFFFF) << 16) | (wqe_index & 0xFFFF);

  // Ring doorbell using system-scope atomic (rocSHMEM pattern)
  __hip_atomic_store(doorbell_ptr, db_val, __ATOMIC_SEQ_CST,
                     __HIP_MEMORY_SCOPE_SYSTEM);

  __threadfence_system();
}

/**
 * Ring IONIC doorbell from CPU
 */
static inline void ionic_ring_doorbell_cpu(volatile uint32_t* doorbell_ptr,
                                           uint32_t qp_id, uint32_t wqe_index) {
  uint32_t db_val = ((qp_id & 0xFFFF) << 16) | (wqe_index & 0xFFFF);
  __atomic_store_n(doorbell_ptr, db_val, __ATOMIC_SEQ_CST);
  __sync_synchronize();
}

#endif // IONIC_RDMA_H
